spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306/mc851?useSSL=false
    username: root
    password: root

#Logging
logging:
  level:
    org:
      springframework:
        web: INFO
    ROOT: WARN
    com:
      mc851: DEBUG